version: '3.4'

networks:
  lan:

services:
  consul:
    image: consul:1.1.0
    hostname: localhost
    networks:
      - lan
    ports:
      - 8500:8500
  postgres:
    image: postgres:11.0
    ports:
      - 5432:5432
    volumes:
         - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: example_app
      PGDATA: /var/lib/postgresql/data/pgdata
  browserless:
    image: browserless/chrome
    hostname: localhost
    networks:
      - lan
    ports:
      - 3000:3000
  

